spring:
  security:
    user:
      name: GM293
      password: password
  h2:
    console:
      enabled: true
  datasource:
    jdbc-url: "jdbc:h2:mem:testdb"
    username: "gm293"
    password: "test"
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:  servlet:
    context-path: /notesApi